apiVersion: apps/v1
kind: Deployment
metadata:
  name: market-data-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: market-data
  template:
    metadata:
      labels:
        app: market-data
    spec:
      containers:
        - name: market-data
          image: 679625721250.dkr.ecr.us-east-1.amazonaws.com/marketpulse-market-data:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "my-kafka:9092"
            - name: FINNHUB_API_KEY
              value: "YOUR_FINNHUB_API_KEY"
---
apiVersion: v1
kind: Service
metadata:
  name: market-data-service
spec:
  selector:
    app: market-data
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP 