name: Build and Deploy market-data

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Build market-data
      - name: Build market-data
        run: mvn clean package -B

      # Debug market-data target folder
      - name: Debug market-data target folder
        run: ls -la target/ || echo "Target folder not found"

      # Upload market-data JAR artifact (for all events)
      - name: Upload market-data JAR
        uses: actions/upload-artifact@v4
        with:
          name: market-data-jar
          path: target/*.jar
        continue-on-error: true

      # Configure AWS credentials (only on push to master)
      - name: Configure AWS Credentials
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      # Upload market-data JAR to S3 (only on push to master)
      - name: Upload market-data JAR to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: aws s3 cp target/*.jar s3://${{ secrets.AWS_S3_BUCKET }}/market-data/ --region ap-south-1
        continue-on-error: true
